[package]
name = "blazing_intelligence_examples"
version = "0.1.0"
edition = "2021"

[dependencies]
blazing_intelligence = { git = "https://github.com/Carloo999/blazing_intelligence" }
nalgebra = { version = "0.33.0"  }
